/**
 * Curated military installations — version-controlled editorial data.
 *
 * Every entry is a publicly documented installation (the kind with a
 * Wikipedia page and decades of open reporting); coordinates are approximate
 * (±~5 km is acceptable for a strategic map) and every row is flagged for
 * editorial review per docs/curation.md. `confidence` rates the coordinate +
 * attribution quality of THIS dataset, not operational status.
 *
 * Honesty rules: no claimed deployments, no inferred aircraft presently
 * stationed, no entries that exist only in speculation. `knownPublicRoles`
 * records long-documented public roles (e.g. "B-52 strategic bomber wing"),
 * not current operations. Where post-2023 status is publicly unclear
 * (e.g. Agadez), status is 'unknown'.
 */

export const MILITARY_SITES_VERSION = 2

export type BaseType =
  | 'air-force-base'
  | 'naval-air-station'
  | 'naval-base'
  | 'joint-base'
  | 'army-aviation'
  | 'strategic-bomber'
  | 'transport-hub'
  | 'training'
  | 'uav'
  | 'air-defense'
  | 'dual-use'

export interface MilitarySite {
  id: string
  name: string
  country: string
  region: string
  lat: number
  lng: number
  branch: 'naval' | 'air' | 'army' | 'joint'
  operator: string
  baseType: BaseType
  status: 'active' | 'inactive' | 'unknown'
  strategicImportance: 'high' | 'medium'
  publicDescription: string
  knownPublicRoles: string[]
  sources: string[]
  confidence: 'high' | 'medium'
  lastUpdated: string
  reviewStatus: 'approved' | 'unreviewed'
  /** 'curated' = the hand-reviewed strategic tier (default); 'public-record'
   *  = bulk OurAirports-derived airbases (smaller, olive markers). */
  tier?: 'curated' | 'public-record'
}

const PUB = ['Public record (Wikipedia/official)']
const NOW = '2026-06-11'

type SiteSeed = Omit<MilitarySite, 'sources' | 'lastUpdated' | 'reviewStatus'>

const seed = (s: SiteSeed): MilitarySite => ({
  ...s,
  sources: PUB,
  lastUpdated: NOW,
  reviewStatus: 'unreviewed',
})

export const MILITARY_SITES: readonly MilitarySite[] = [
  /* ── United States — CONUS ─────────────────────────────────────────────── */
  seed({ id: 'us-andrews', name: 'Joint Base Andrews', country: 'United States', region: 'North America', lat: 38.81, lng: -76.87, branch: 'joint', operator: 'United States', baseType: 'transport-hub', status: 'active', strategicImportance: 'high', publicDescription: 'Presidential and government air transport hub near Washington DC.', knownPublicRoles: ['VIP/state transport (SAM)'], confidence: 'high' }),
  seed({ id: 'us-whiteman', name: 'Whiteman AFB', country: 'United States', region: 'North America', lat: 38.73, lng: -93.55, branch: 'air', operator: 'United States', baseType: 'strategic-bomber', status: 'active', strategicImportance: 'high', publicDescription: 'Long-documented home of the B-2 stealth bomber fleet.', knownPublicRoles: ['B-2 strategic bomber wing'], confidence: 'high' }),
  seed({ id: 'us-minot', name: 'Minot AFB', country: 'United States', region: 'North America', lat: 48.42, lng: -101.33, branch: 'air', operator: 'United States', baseType: 'strategic-bomber', status: 'active', strategicImportance: 'high', publicDescription: 'Dual-mission strategic base: bombers and ICBM wing.', knownPublicRoles: ['B-52 wing', 'Minuteman III ICBM wing'], confidence: 'high' }),
  seed({ id: 'us-barksdale', name: 'Barksdale AFB', country: 'United States', region: 'North America', lat: 32.5, lng: -93.66, branch: 'air', operator: 'United States', baseType: 'strategic-bomber', status: 'active', strategicImportance: 'high', publicDescription: 'Headquarters of Air Force Global Strike Command.', knownPublicRoles: ['B-52 strategic bomber wing'], confidence: 'high' }),
  seed({ id: 'us-dyess', name: 'Dyess AFB', country: 'United States', region: 'North America', lat: 32.42, lng: -99.85, branch: 'air', operator: 'United States', baseType: 'strategic-bomber', status: 'active', strategicImportance: 'medium', publicDescription: 'B-1B bomber base in Texas.', knownPublicRoles: ['B-1B bomber wing'], confidence: 'high' }),
  seed({ id: 'us-ellsworth', name: 'Ellsworth AFB', country: 'United States', region: 'North America', lat: 44.14, lng: -103.1, branch: 'air', operator: 'United States', baseType: 'strategic-bomber', status: 'active', strategicImportance: 'medium', publicDescription: 'B-1B base; announced first B-21 main operating base.', knownPublicRoles: ['B-1B bomber wing'], confidence: 'high' }),
  seed({ id: 'us-offutt', name: 'Offutt AFB', country: 'United States', region: 'North America', lat: 41.12, lng: -95.92, branch: 'air', operator: 'United States', baseType: 'air-force-base', status: 'active', strategicImportance: 'high', publicDescription: 'US Strategic Command headquarters; reconnaissance wing.', knownPublicRoles: ['RC-135 ISR wing', 'STRATCOM HQ'], confidence: 'high' }),
  seed({ id: 'us-beale', name: 'Beale AFB', country: 'United States', region: 'North America', lat: 39.14, lng: -121.44, branch: 'air', operator: 'United States', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'High-altitude reconnaissance base.', knownPublicRoles: ['U-2 / RQ-4 ISR operations'], confidence: 'high' }),
  seed({ id: 'us-creech', name: 'Creech AFB', country: 'United States', region: 'North America', lat: 36.59, lng: -115.67, branch: 'air', operator: 'United States', baseType: 'uav', status: 'active', strategicImportance: 'medium', publicDescription: 'Publicly documented hub of remotely piloted aircraft operations.', knownPublicRoles: ['MQ-9 remote operations'], confidence: 'high' }),
  seed({ id: 'us-nellis', name: 'Nellis AFB', country: 'United States', region: 'North America', lat: 36.24, lng: -115.03, branch: 'air', operator: 'United States', baseType: 'training', status: 'active', strategicImportance: 'medium', publicDescription: 'Advanced air combat training (Red Flag).', knownPublicRoles: ['Aggressor/training wings'], confidence: 'high' }),
  seed({ id: 'us-edwards', name: 'Edwards AFB', country: 'United States', region: 'North America', lat: 34.91, lng: -117.88, branch: 'air', operator: 'United States', baseType: 'training', status: 'active', strategicImportance: 'medium', publicDescription: 'Flight test center.', knownPublicRoles: ['Flight test'], confidence: 'high' }),
  seed({ id: 'us-eglin', name: 'Eglin AFB', country: 'United States', region: 'North America', lat: 30.46, lng: -86.55, branch: 'air', operator: 'United States', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Weapons development and test center; F-35 training.', knownPublicRoles: ['Test & evaluation', 'F-35 training'], confidence: 'high' }),
  seed({ id: 'us-macdill', name: 'MacDill AFB', country: 'United States', region: 'North America', lat: 27.85, lng: -82.5, branch: 'air', operator: 'United States', baseType: 'air-force-base', status: 'active', strategicImportance: 'high', publicDescription: 'CENTCOM and SOCOM headquarters; tanker wing.', knownPublicRoles: ['KC-135 tanker wing', 'CENTCOM/SOCOM HQ'], confidence: 'high' }),
  seed({ id: 'us-tinker', name: 'Tinker AFB', country: 'United States', region: 'North America', lat: 35.42, lng: -97.39, branch: 'air', operator: 'United States', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'AWACS home base and depot maintenance center.', knownPublicRoles: ['E-3 AWACS wing'], confidence: 'high' }),
  seed({ id: 'us-fairchild', name: 'Fairchild AFB', country: 'United States', region: 'North America', lat: 47.62, lng: -117.66, branch: 'air', operator: 'United States', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Tanker base in the Pacific Northwest.', knownPublicRoles: ['KC-135 tanker wing'], confidence: 'high' }),
  seed({ id: 'us-travis', name: 'Travis AFB', country: 'United States', region: 'North America', lat: 38.27, lng: -121.93, branch: 'air', operator: 'United States', baseType: 'transport-hub', status: 'active', strategicImportance: 'medium', publicDescription: 'Pacific-facing strategic airlift hub.', knownPublicRoles: ['C-5/C-17/KC-10 airlift & tanker'], confidence: 'high' }),
  seed({ id: 'us-dover', name: 'Dover AFB', country: 'United States', region: 'North America', lat: 39.13, lng: -75.47, branch: 'air', operator: 'United States', baseType: 'transport-hub', status: 'active', strategicImportance: 'medium', publicDescription: 'Atlantic-facing strategic airlift hub.', knownPublicRoles: ['C-5/C-17 airlift'], confidence: 'high' }),
  seed({ id: 'us-jblm', name: 'Joint Base Lewis-McChord', country: 'United States', region: 'North America', lat: 47.14, lng: -122.48, branch: 'joint', operator: 'United States', baseType: 'joint-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Army corps base with co-located airlift wing.', knownPublicRoles: ['C-17 airlift', 'Army aviation'], confidence: 'high' }),
  seed({ id: 'us-oceana', name: 'NAS Oceana', country: 'United States', region: 'North America', lat: 36.82, lng: -76.03, branch: 'naval', operator: 'United States', baseType: 'naval-air-station', status: 'active', strategicImportance: 'medium', publicDescription: 'US Navy east-coast strike fighter master jet base.', knownPublicRoles: ['F/A-18 fleet squadrons'], confidence: 'high' }),
  seed({ id: 'us-whidbey', name: 'NAS Whidbey Island', country: 'United States', region: 'North America', lat: 48.35, lng: -122.66, branch: 'naval', operator: 'United States', baseType: 'naval-air-station', status: 'active', strategicImportance: 'medium', publicDescription: 'Electronic attack and maritime patrol aviation base.', knownPublicRoles: ['EA-18G squadrons', 'P-8 patrol'], confidence: 'high' }),
  seed({ id: 'us-jacksonville', name: 'NAS Jacksonville', country: 'United States', region: 'North America', lat: 30.23, lng: -81.68, branch: 'naval', operator: 'United States', baseType: 'naval-air-station', status: 'active', strategicImportance: 'medium', publicDescription: 'Maritime patrol and anti-submarine aviation base.', knownPublicRoles: ['P-8 maritime patrol'], confidence: 'high' }),
  seed({ id: 'us-norfolk', name: 'Naval Station Norfolk', country: 'United States', region: 'North America', lat: 36.95, lng: -76.31, branch: 'naval', operator: 'United States', baseType: 'naval-base', status: 'active', strategicImportance: 'high', publicDescription: 'Largest naval station in the world; Atlantic Fleet home port.', knownPublicRoles: ['Carrier home port'], confidence: 'high' }),

  /* ── United States — Alaska & Indo-Pacific ─────────────────────────────── */
  seed({ id: 'us-jber', name: 'JB Elmendorf-Richardson', country: 'United States', region: 'North America', lat: 61.25, lng: -149.81, branch: 'joint', operator: 'United States', baseType: 'joint-base', status: 'active', strategicImportance: 'high', publicDescription: 'Arctic/Pacific air power hub in Alaska.', knownPublicRoles: ['F-22 wing', 'Airlift'], confidence: 'high' }),
  seed({ id: 'us-eielson', name: 'Eielson AFB', country: 'United States', region: 'North America', lat: 64.67, lng: -147.1, branch: 'air', operator: 'United States', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Interior-Alaska fighter base.', knownPublicRoles: ['F-35 wing'], confidence: 'high' }),
  seed({ id: 'us-hickam', name: 'JB Pearl Harbor-Hickam', country: 'United States', region: 'Indo-Pacific', lat: 21.32, lng: -157.95, branch: 'joint', operator: 'United States', baseType: 'joint-base', status: 'active', strategicImportance: 'high', publicDescription: 'INDOPACOM hub; fleet home port with co-located air wing.', knownPublicRoles: ['Pacific Fleet home port', 'Airlift/fighter wings'], confidence: 'high' }),
  seed({ id: 'us-andersen', name: 'Andersen AFB', country: 'Guam', region: 'Indo-Pacific', lat: 13.58, lng: 144.93, branch: 'air', operator: 'United States', baseType: 'strategic-bomber', status: 'active', strategicImportance: 'high', publicDescription: 'Western Pacific bomber and tanker forward operating base.', knownPublicRoles: ['Bomber task force rotations'], confidence: 'high' }),
  seed({ id: 'us-guam-naval', name: 'Naval Base Guam', country: 'Guam', region: 'Indo-Pacific', lat: 13.43, lng: 144.66, branch: 'naval', operator: 'United States', baseType: 'naval-base', status: 'active', strategicImportance: 'high', publicDescription: 'Forward submarine and expeditionary base in the Marianas.', knownPublicRoles: ['Attack submarine squadron'], confidence: 'high' }),
  seed({ id: 'us-kadena', name: 'Kadena Air Base', country: 'Japan', region: 'Indo-Pacific', lat: 26.36, lng: 127.77, branch: 'air', operator: 'United States / Japan', baseType: 'air-force-base', status: 'active', strategicImportance: 'high', publicDescription: 'Largest US air base in the western Pacific (Okinawa).', knownPublicRoles: ['Fighter/ISR/tanker wings'], confidence: 'high' }),
  seed({ id: 'us-yokota', name: 'Yokota Air Base', country: 'Japan', region: 'Indo-Pacific', lat: 35.75, lng: 139.35, branch: 'air', operator: 'United States / Japan', baseType: 'transport-hub', status: 'active', strategicImportance: 'medium', publicDescription: 'US Forces Japan headquarters and airlift hub.', knownPublicRoles: ['C-130 airlift wing'], confidence: 'high' }),
  seed({ id: 'us-misawa', name: 'Misawa Air Base', country: 'Japan', region: 'Indo-Pacific', lat: 40.7, lng: 141.37, branch: 'air', operator: 'United States / Japan', baseType: 'dual-use', status: 'active', strategicImportance: 'medium', publicDescription: 'Joint US-Japan fighter and surveillance base in northern Honshu.', knownPublicRoles: ['F-16 wing', 'JASDF units'], confidence: 'high' }),
  seed({ id: 'us-iwakuni', name: 'MCAS Iwakuni', country: 'Japan', region: 'Indo-Pacific', lat: 34.14, lng: 132.24, branch: 'naval', operator: 'United States / Japan', baseType: 'naval-air-station', status: 'active', strategicImportance: 'medium', publicDescription: 'Marine corps air station hosting carrier air wing elements.', knownPublicRoles: ['F-35B/F/A-18 squadrons'], confidence: 'high' }),
  seed({ id: 'us-yokosuka', name: 'Fleet Activities Yokosuka', country: 'Japan', region: 'Indo-Pacific', lat: 35.29, lng: 139.67, branch: 'naval', operator: 'United States / Japan', baseType: 'naval-base', status: 'active', strategicImportance: 'high', publicDescription: 'Forward-deployed carrier strike group home port.', knownPublicRoles: ['7th Fleet flagship/carrier home port'], confidence: 'high' }),
  seed({ id: 'us-osan', name: 'Osan Air Base', country: 'South Korea', region: 'Indo-Pacific', lat: 37.09, lng: 127.03, branch: 'air', operator: 'United States / South Korea', baseType: 'air-force-base', status: 'active', strategicImportance: 'high', publicDescription: 'Seventh Air Force headquarters on the Korean peninsula.', knownPublicRoles: ['F-16/A-10 wing', 'U-2 detachment'], confidence: 'high' }),
  seed({ id: 'us-kunsan', name: 'Kunsan Air Base', country: 'South Korea', region: 'Indo-Pacific', lat: 35.9, lng: 126.62, branch: 'air', operator: 'United States / South Korea', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Fighter base on Korea’s west coast.', knownPublicRoles: ['F-16 wing'], confidence: 'high' }),

  /* ── Europe / NATO ──────────────────────────────────────────────────────── */
  seed({ id: 'us-ramstein', name: 'Ramstein Air Base', country: 'Germany', region: 'Europe', lat: 49.44, lng: 7.6, branch: 'air', operator: 'United States / NATO', baseType: 'transport-hub', status: 'active', strategicImportance: 'high', publicDescription: 'USAFE and NATO Allied Air Command headquarters; airlift hub.', knownPublicRoles: ['Airlift hub', 'HQ functions'], confidence: 'high' }),
  seed({ id: 'us-spangdahlem', name: 'Spangdahlem Air Base', country: 'Germany', region: 'Europe', lat: 49.97, lng: 6.69, branch: 'air', operator: 'United States', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'US fighter base in the Eifel.', knownPublicRoles: ['F-16 wing'], confidence: 'high' }),
  seed({ id: 'de-buechel', name: 'Büchel Air Base', country: 'Germany', region: 'Europe', lat: 50.17, lng: 7.06, branch: 'air', operator: 'Germany / NATO', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'German Tornado base, publicly associated with NATO nuclear sharing.', knownPublicRoles: ['Tornado wing'], confidence: 'medium' }),
  seed({ id: 'uk-lakenheath', name: 'RAF Lakenheath', country: 'United Kingdom', region: 'Europe', lat: 52.41, lng: 0.56, branch: 'air', operator: 'United States', baseType: 'air-force-base', status: 'active', strategicImportance: 'high', publicDescription: 'Largest USAF fighter operation in Europe.', knownPublicRoles: ['F-35/F-15 wings'], confidence: 'high' }),
  seed({ id: 'uk-mildenhall', name: 'RAF Mildenhall', country: 'United Kingdom', region: 'Europe', lat: 52.36, lng: 0.49, branch: 'air', operator: 'United States', baseType: 'air-force-base', status: 'active', strategicImportance: 'high', publicDescription: 'US tanker and special operations air hub in Europe.', knownPublicRoles: ['KC-135 tankers', 'ISR aircraft'], confidence: 'high' }),
  seed({ id: 'uk-fairford', name: 'RAF Fairford', country: 'United Kingdom', region: 'Europe', lat: 51.68, lng: -1.79, branch: 'air', operator: 'United States / United Kingdom', baseType: 'strategic-bomber', status: 'active', strategicImportance: 'medium', publicDescription: 'Forward operating location for US bomber task forces.', knownPublicRoles: ['Bomber deployments'], confidence: 'high' }),
  seed({ id: 'uk-brize', name: 'RAF Brize Norton', country: 'United Kingdom', region: 'Europe', lat: 51.75, lng: -1.58, branch: 'air', operator: 'United Kingdom', baseType: 'transport-hub', status: 'active', strategicImportance: 'medium', publicDescription: 'RAF strategic air transport and tanker hub.', knownPublicRoles: ['Voyager/A400M/C-17 fleets'], confidence: 'high' }),
  seed({ id: 'uk-coningsby', name: 'RAF Coningsby', country: 'United Kingdom', region: 'Europe', lat: 53.09, lng: -0.17, branch: 'air', operator: 'United Kingdom', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Typhoon main operating base and QRA station.', knownPublicRoles: ['Typhoon squadrons', 'Quick reaction alert'], confidence: 'high' }),
  seed({ id: 'uk-lossiemouth', name: 'RAF Lossiemouth', country: 'United Kingdom', region: 'Europe', lat: 57.71, lng: -3.34, branch: 'air', operator: 'United Kingdom', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Typhoon and maritime patrol base in Scotland.', knownPublicRoles: ['P-8 maritime patrol', 'Typhoon QRA'], confidence: 'high' }),
  seed({ id: 'uk-akrotiri', name: 'RAF Akrotiri', country: 'Cyprus', region: 'Europe', lat: 34.59, lng: 32.99, branch: 'air', operator: 'United Kingdom', baseType: 'air-force-base', status: 'active', strategicImportance: 'high', publicDescription: 'UK sovereign base; eastern Mediterranean operations hub.', knownPublicRoles: ['Typhoon deployments', 'ISR staging'], confidence: 'high' }),
  seed({ id: 'it-aviano', name: 'Aviano Air Base', country: 'Italy', region: 'Europe', lat: 46.03, lng: 12.6, branch: 'air', operator: 'United States / Italy', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'US fighter wing in northeastern Italy.', knownPublicRoles: ['F-16 wing'], confidence: 'high' }),
  seed({ id: 'it-sigonella', name: 'NAS Sigonella', country: 'Italy', region: 'Europe', lat: 37.4, lng: 14.92, branch: 'naval', operator: 'United States / Italy / NATO', baseType: 'naval-air-station', status: 'active', strategicImportance: 'high', publicDescription: 'Mediterranean maritime patrol and UAV hub (Sicily).', knownPublicRoles: ['P-8 patrol', 'NATO AGS RQ-4'], confidence: 'high' }),
  seed({ id: 'it-ghedi', name: 'Ghedi Air Base', country: 'Italy', region: 'Europe', lat: 45.43, lng: 10.27, branch: 'air', operator: 'Italy / NATO', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Italian Tornado base, publicly associated with NATO nuclear sharing.', knownPublicRoles: ['Tornado wing'], confidence: 'medium' }),
  seed({ id: 'es-rota', name: 'Naval Station Rota', country: 'Spain', region: 'Europe', lat: 36.64, lng: -6.35, branch: 'naval', operator: 'United States / Spain', baseType: 'naval-base', status: 'active', strategicImportance: 'high', publicDescription: 'Forward home port for US Aegis destroyers; airlift stop.', knownPublicRoles: ['Destroyer squadron', 'Airlift staging'], confidence: 'high' }),
  seed({ id: 'es-moron', name: 'Morón Air Base', country: 'Spain', region: 'Europe', lat: 37.17, lng: -5.62, branch: 'air', operator: 'United States / Spain', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Tanker and crisis-response staging base in Andalusia.', knownPublicRoles: ['Tanker deployments'], confidence: 'medium' }),
  seed({ id: 'pt-lajes', name: 'Lajes Field', country: 'Portugal', region: 'Europe', lat: 38.76, lng: -27.09, branch: 'air', operator: 'Portugal / United States', baseType: 'transport-hub', status: 'active', strategicImportance: 'medium', publicDescription: 'Mid-Atlantic refueling and transit field (Azores).', knownPublicRoles: ['Transatlantic staging'], confidence: 'high' }),
  seed({ id: 'nato-geilenkirchen', name: 'NATO AB Geilenkirchen', country: 'Germany', region: 'Europe', lat: 50.96, lng: 6.04, branch: 'air', operator: 'NATO', baseType: 'air-force-base', status: 'active', strategicImportance: 'high', publicDescription: 'Home of the NATO E-3A AWACS component.', knownPublicRoles: ['E-3 AWACS fleet'], confidence: 'high' }),
  seed({ id: 'nl-eindhoven', name: 'Eindhoven Air Base', country: 'Netherlands', region: 'Europe', lat: 51.45, lng: 5.37, branch: 'air', operator: 'Netherlands / EU MCC', baseType: 'transport-hub', status: 'active', strategicImportance: 'medium', publicDescription: 'European multinational tanker-transport fleet base.', knownPublicRoles: ['MRTT tanker fleet'], confidence: 'high' }),
  seed({ id: 'nl-volkel', name: 'Volkel Air Base', country: 'Netherlands', region: 'Europe', lat: 51.66, lng: 5.71, branch: 'air', operator: 'Netherlands / NATO', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Dutch F-35 base, publicly associated with NATO nuclear sharing.', knownPublicRoles: ['F-35 squadrons'], confidence: 'medium' }),
  seed({ id: 'be-kleinebrogel', name: 'Kleine Brogel Air Base', country: 'Belgium', region: 'Europe', lat: 51.17, lng: 5.47, branch: 'air', operator: 'Belgium / NATO', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Belgian fighter base, publicly associated with NATO nuclear sharing.', knownPublicRoles: ['F-16/F-35 squadrons'], confidence: 'medium' }),
  seed({ id: 'fr-istres', name: 'Istres-Le Tubé Air Base', country: 'France', region: 'Europe', lat: 43.52, lng: 4.92, branch: 'air', operator: 'France', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'French strategic tanker base and test center.', knownPublicRoles: ['MRTT tanker fleet'], confidence: 'high' }),
  seed({ id: 'fr-evreux', name: 'Évreux-Fauville Air Base', country: 'France', region: 'Europe', lat: 49.03, lng: 1.22, branch: 'air', operator: 'France', baseType: 'transport-hub', status: 'active', strategicImportance: 'medium', publicDescription: 'French tactical transport base.', knownPublicRoles: ['C-130/Casa transport'], confidence: 'medium' }),
  seed({ id: 'no-orland', name: 'Ørland Air Station', country: 'Norway', region: 'Europe', lat: 63.7, lng: 9.6, branch: 'air', operator: 'Norway', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Norwegian F-35 main operating base.', knownPublicRoles: ['F-35 squadrons'], confidence: 'high' }),
  seed({ id: 'is-keflavik', name: 'Keflavik Air Base', country: 'Iceland', region: 'Europe', lat: 63.98, lng: -22.6, branch: 'air', operator: 'NATO / Iceland', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'North Atlantic air policing and maritime patrol staging.', knownPublicRoles: ['Air policing rotations', 'P-8 detachments'], confidence: 'high' }),
  seed({ id: 'ee-amari', name: 'Ämari Air Base', country: 'Estonia', region: 'Europe', lat: 59.26, lng: 24.21, branch: 'air', operator: 'Estonia / NATO', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Baltic air policing base.', knownPublicRoles: ['NATO air policing rotations'], confidence: 'high' }),
  seed({ id: 'lt-siauliai', name: 'Šiauliai Air Base', country: 'Lithuania', region: 'Europe', lat: 55.89, lng: 23.39, branch: 'air', operator: 'Lithuania / NATO', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Primary Baltic air policing base.', knownPublicRoles: ['NATO air policing rotations'], confidence: 'high' }),
  seed({ id: 'pl-powidz', name: 'Powidz Air Base', country: 'Poland', region: 'Europe', lat: 52.38, lng: 17.85, branch: 'air', operator: 'Poland / United States', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Polish transport base and US Army aviation prepositioning site.', knownPublicRoles: ['C-130 transport', 'US rotational aviation'], confidence: 'medium' }),
  seed({ id: 'ro-kogalniceanu', name: 'Mihail Kogălniceanu AB', country: 'Romania', region: 'Europe', lat: 44.36, lng: 28.49, branch: 'air', operator: 'Romania / NATO', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Black Sea regional hub for NATO rotational forces.', knownPublicRoles: ['Rotational deployments'], confidence: 'high' }),
  seed({ id: 'gr-souda', name: 'Souda Bay (NSA Crete)', country: 'Greece', region: 'Europe', lat: 35.49, lng: 24.15, branch: 'naval', operator: 'Greece / United States', baseType: 'naval-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Eastern Mediterranean naval support and air staging.', knownPublicRoles: ['Naval support', 'Air detachments'], confidence: 'high' }),

  /* ── Middle East ────────────────────────────────────────────────────────── */
  seed({ id: 'us-aludeid', name: 'Al Udeid Air Base', country: 'Qatar', region: 'Middle East', lat: 25.12, lng: 51.32, branch: 'air', operator: 'United States / Qatar', baseType: 'air-force-base', status: 'active', strategicImportance: 'high', publicDescription: 'Largest US air base in the Middle East; CENTCOM air operations center.', knownPublicRoles: ['Tanker/transport/ISR hub'], confidence: 'high' }),
  seed({ id: 'us-aldhafra', name: 'Al Dhafra Air Base', country: 'United Arab Emirates', region: 'Middle East', lat: 24.25, lng: 54.55, branch: 'air', operator: 'United States / UAE', baseType: 'air-force-base', status: 'active', strategicImportance: 'high', publicDescription: 'Gulf fighter and ISR base.', knownPublicRoles: ['Fighter/ISR deployments'], confidence: 'high' }),
  seed({ id: 'us-alisalem', name: 'Ali Al Salem Air Base', country: 'Kuwait', region: 'Middle East', lat: 29.35, lng: 47.52, branch: 'air', operator: 'United States / Kuwait', baseType: 'transport-hub', status: 'active', strategicImportance: 'medium', publicDescription: 'Theater airlift hub in Kuwait.', knownPublicRoles: ['C-130 airlift'], confidence: 'medium' }),
  seed({ id: 'sa-pSAB', name: 'Prince Sultan Air Base', country: 'Saudi Arabia', region: 'Middle East', lat: 24.06, lng: 47.58, branch: 'air', operator: 'Saudi Arabia / United States', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Saudi base hosting rotational US air and air-defense units.', knownPublicRoles: ['Rotational deployments'], confidence: 'medium' }),
  seed({ id: 'jo-azraq', name: 'Muwaffaq Salti Air Base (Azraq)', country: 'Jordan', region: 'Middle East', lat: 31.83, lng: 36.78, branch: 'air', operator: 'Jordan / United States', baseType: 'uav', status: 'active', strategicImportance: 'medium', publicDescription: 'Jordanian base publicly reported hosting coalition UAV and fighter dets.', knownPublicRoles: ['Coalition air detachments'], confidence: 'medium' }),
  seed({ id: 'us-bahrain', name: 'NSA Bahrain (US 5th Fleet)', country: 'Bahrain', region: 'Middle East', lat: 26.21, lng: 50.61, branch: 'naval', operator: 'United States', baseType: 'naval-base', status: 'active', strategicImportance: 'high', publicDescription: 'US Navy 5th Fleet headquarters.', knownPublicRoles: ['Fleet HQ'], confidence: 'high' }),
  seed({ id: 'il-nevatim', name: 'Nevatim Air Base', country: 'Israel', region: 'Middle East', lat: 31.21, lng: 35.01, branch: 'air', operator: 'Israel', baseType: 'air-force-base', status: 'active', strategicImportance: 'high', publicDescription: 'Major Israeli air base; publicly documented F-35 home base.', knownPublicRoles: ['F-35 squadrons', 'Transport wing'], confidence: 'high' }),
  seed({ id: 'il-ramatdavid', name: 'Ramat David Air Base', country: 'Israel', region: 'Middle East', lat: 32.67, lng: 35.18, branch: 'air', operator: 'Israel', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Northern-Israel fighter base.', knownPublicRoles: ['F-16 squadrons'], confidence: 'medium' }),
  seed({ id: 'tr-incirlik', name: 'Incirlik Air Base', country: 'Turkey', region: 'Middle East', lat: 37.0, lng: 35.43, branch: 'air', operator: 'Turkey / United States / NATO', baseType: 'air-force-base', status: 'active', strategicImportance: 'high', publicDescription: 'Joint Turkish-US base near Adana.', knownPublicRoles: ['Tanker wing', 'Rotational deployments'], confidence: 'high' }),

  /* ── Russia ─────────────────────────────────────────────────────────────── */
  seed({ id: 'ru-engels', name: 'Engels-2 Air Base', country: 'Russia', region: 'Russia', lat: 51.48, lng: 46.21, branch: 'air', operator: 'Russia', baseType: 'strategic-bomber', status: 'active', strategicImportance: 'high', publicDescription: 'Primary Russian strategic bomber base (long public record).', knownPublicRoles: ['Tu-95/Tu-160 regiments'], confidence: 'high' }),
  seed({ id: 'ru-olenya', name: 'Olenya Air Base', country: 'Russia', region: 'Russia', lat: 68.15, lng: 33.46, branch: 'air', operator: 'Russia', baseType: 'strategic-bomber', status: 'active', strategicImportance: 'high', publicDescription: 'Kola peninsula bomber base, widely documented in open sources.', knownPublicRoles: ['Bomber dispersal/operations'], confidence: 'medium' }),
  seed({ id: 'ru-hmeimim', name: 'Hmeimim Air Base', country: 'Syria', region: 'Middle East', lat: 35.4, lng: 35.95, branch: 'air', operator: 'Russia', baseType: 'air-force-base', status: 'unknown', strategicImportance: 'high', publicDescription: 'Russian expeditionary air base in Syria; post-2024 posture publicly unclear.', knownPublicRoles: ['Expeditionary air group'], confidence: 'high' }),
  seed({ id: 'ru-tartus', name: 'Tartus Naval Facility', country: 'Syria', region: 'Middle East', lat: 34.9, lng: 35.87, branch: 'naval', operator: 'Russia', baseType: 'naval-base', status: 'unknown', strategicImportance: 'medium', publicDescription: 'Russian Mediterranean replenishment point; post-2024 posture publicly unclear.', knownPublicRoles: ['Naval logistics'], confidence: 'high' }),
  seed({ id: 'ru-belbek', name: 'Belbek Air Base', country: 'Crimea (occupied Ukraine)', region: 'Russia', lat: 44.69, lng: 33.57, branch: 'air', operator: 'Russia', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Fighter base near Sevastopol, frequent subject of open-source reporting.', knownPublicRoles: ['Fighter regiments'], confidence: 'medium' }),
  seed({ id: 'ru-saky', name: 'Saky Air Base', country: 'Crimea (occupied Ukraine)', region: 'Russia', lat: 45.09, lng: 33.59, branch: 'naval', operator: 'Russia', baseType: 'naval-air-station', status: 'active', strategicImportance: 'medium', publicDescription: 'Naval aviation base in western Crimea.', knownPublicRoles: ['Naval aviation regiments'], confidence: 'medium' }),
  seed({ id: 'ru-lipetsk', name: 'Lipetsk Air Base', country: 'Russia', region: 'Russia', lat: 52.63, lng: 39.45, branch: 'air', operator: 'Russia', baseType: 'training', status: 'active', strategicImportance: 'medium', publicDescription: 'Russian combat-training and aircrew conversion center.', knownPublicRoles: ['Combat training center'], confidence: 'medium' }),

  /* ── China / Indo-Pacific others ────────────────────────────────────────── */
  seed({ id: 'cn-yulin', name: 'Yulin Naval Base', country: 'China', region: 'Indo-Pacific', lat: 18.21, lng: 109.55, branch: 'naval', operator: 'China', baseType: 'naval-base', status: 'active', strategicImportance: 'high', publicDescription: 'Hainan submarine base, extensively documented in open-source imagery.', knownPublicRoles: ['Submarine base'], confidence: 'medium' }),
  seed({ id: 'cn-lingshui', name: 'Lingshui Air Base', country: 'China', region: 'Indo-Pacific', lat: 18.51, lng: 110.05, branch: 'air', operator: 'China', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Hainan air base associated in public reporting with maritime ISR.', knownPublicRoles: ['Maritime ISR'], confidence: 'medium' }),
  seed({ id: 'cn-djibouti', name: 'PLA Support Base Djibouti', country: 'Djibouti', region: 'Africa', lat: 11.59, lng: 43.06, branch: 'naval', operator: 'China', baseType: 'naval-base', status: 'active', strategicImportance: 'high', publicDescription: 'China’s first overseas military base.', knownPublicRoles: ['Naval logistics'], confidence: 'high' }),
  seed({ id: 'us-diego-garcia', name: 'Diego Garcia', country: 'British Indian Ocean Territory', region: 'Indo-Pacific', lat: -7.31, lng: 72.41, branch: 'joint', operator: 'United States / United Kingdom', baseType: 'strategic-bomber', status: 'active', strategicImportance: 'high', publicDescription: 'Indian Ocean strategic island base.', knownPublicRoles: ['Bomber staging', 'Naval support'], confidence: 'high' }),

  /* ── South Asia ─────────────────────────────────────────────────────────── */
  seed({ id: 'in-hindon', name: 'Hindon Air Force Station', country: 'India', region: 'South Asia', lat: 28.71, lng: 77.36, branch: 'air', operator: 'India', baseType: 'transport-hub', status: 'active', strategicImportance: 'medium', publicDescription: 'Major IAF transport base near Delhi.', knownPublicRoles: ['C-17/C-130 fleets'], confidence: 'medium' }),
  seed({ id: 'in-ambala', name: 'Ambala Air Force Station', country: 'India', region: 'South Asia', lat: 30.37, lng: 76.82, branch: 'air', operator: 'India', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Frontline IAF fighter base; first Rafale squadron home.', knownPublicRoles: ['Rafale squadrons'], confidence: 'medium' }),
  seed({ id: 'in-agra', name: 'Agra Air Force Station', country: 'India', region: 'South Asia', lat: 27.16, lng: 77.96, branch: 'air', operator: 'India', baseType: 'transport-hub', status: 'active', strategicImportance: 'medium', publicDescription: 'IAF transport and tanker base.', knownPublicRoles: ['Il-76/tanker fleets'], confidence: 'medium' }),
  seed({ id: 'pk-nurkhan', name: 'PAF Base Nur Khan', country: 'Pakistan', region: 'South Asia', lat: 33.62, lng: 73.1, branch: 'air', operator: 'Pakistan', baseType: 'transport-hub', status: 'active', strategicImportance: 'medium', publicDescription: 'PAF transport and VIP base at Rawalpindi.', knownPublicRoles: ['Transport/VIP fleets'], confidence: 'medium' }),
  seed({ id: 'pk-masroor', name: 'PAF Base Masroor', country: 'Pakistan', region: 'South Asia', lat: 24.89, lng: 66.94, branch: 'air', operator: 'Pakistan', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Large PAF base near Karachi.', knownPublicRoles: ['Fighter squadrons'], confidence: 'medium' }),

  /* ── Oceania ────────────────────────────────────────────────────────────── */
  seed({ id: 'au-amberley', name: 'RAAF Base Amberley', country: 'Australia', region: 'Oceania', lat: -27.64, lng: 152.71, branch: 'air', operator: 'Australia', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Largest RAAF base; strike and tanker fleets.', knownPublicRoles: ['F/A-18F', 'KC-30 tankers'], confidence: 'high' }),
  seed({ id: 'au-tindal', name: 'RAAF Base Tindal', country: 'Australia', region: 'Oceania', lat: -14.52, lng: 132.38, branch: 'air', operator: 'Australia / United States', baseType: 'air-force-base', status: 'active', strategicImportance: 'high', publicDescription: 'Northern Australia fighter base; publicly announced US bomber rotations.', knownPublicRoles: ['F-35 squadrons', 'Bomber rotations'], confidence: 'medium' }),
  seed({ id: 'au-edinburgh', name: 'RAAF Base Edinburgh', country: 'Australia', region: 'Oceania', lat: -34.7, lng: 138.62, branch: 'air', operator: 'Australia', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'ISR and maritime patrol base.', knownPublicRoles: ['P-8 patrol', 'ISR fleets'], confidence: 'medium' }),

  /* ── Africa & Latin America ─────────────────────────────────────────────── */
  seed({ id: 'us-lemonnier', name: 'Camp Lemonnier', country: 'Djibouti', region: 'Africa', lat: 11.54, lng: 43.15, branch: 'joint', operator: 'United States', baseType: 'joint-base', status: 'active', strategicImportance: 'high', publicDescription: 'Primary US base in Africa, adjacent to Djibouti airport.', knownPublicRoles: ['Joint operations hub'], confidence: 'high' }),
  seed({ id: 'fr-djibouti', name: 'French Forces Djibouti', country: 'Djibouti', region: 'Africa', lat: 11.55, lng: 43.16, branch: 'joint', operator: 'France', baseType: 'joint-base', status: 'active', strategicImportance: 'medium', publicDescription: 'France’s largest overseas military presence.', knownPublicRoles: ['Fighter/transport detachments'], confidence: 'high' }),
  seed({ id: 'ne-agadez', name: 'Air Base 201 (Agadez)', country: 'Niger', region: 'Africa', lat: 16.97, lng: 7.99, branch: 'air', operator: 'Niger (US-built)', baseType: 'uav', status: 'unknown', strategicImportance: 'medium', publicDescription: 'US-built UAV base; US withdrawal publicly reported 2024 — current use unclear.', knownPublicRoles: ['Former US UAV operations'], confidence: 'medium' }),
  seed({ id: 'hn-sotocano', name: 'Soto Cano Air Base', country: 'Honduras', region: 'Latin America', lat: 14.38, lng: -87.62, branch: 'joint', operator: 'Honduras / United States', baseType: 'joint-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Hosts US Joint Task Force-Bravo.', knownPublicRoles: ['Helicopter/transport operations'], confidence: 'medium' }),
  seed({ id: 'br-anapolis', name: 'Anápolis Air Base', country: 'Brazil', region: 'Latin America', lat: -16.23, lng: -48.96, branch: 'air', operator: 'Brazil', baseType: 'air-force-base', status: 'active', strategicImportance: 'medium', publicDescription: 'Brazilian fighter base (F-39 Gripen).', knownPublicRoles: ['Gripen squadrons'], confidence: 'medium' }),
] as const

export const BASE_TYPES: readonly BaseType[] = [
  'air-force-base', 'naval-air-station', 'naval-base', 'joint-base', 'army-aviation',
  'strategic-bomber', 'transport-hub', 'training', 'uav', 'air-defense', 'dual-use',
] as const
